# Generated by Django 5.2.3 on 2025-06-30 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstMessage', '0002_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='tinestamp',
            new_name='timestamp',
        ),
    ]
